<?php
/**
* Implementation of hook_permission().
*/
function campaign_thermometer_permission() {
  return array(
    'access campaign_thermometer' => array('title' => t('Campaign Thermometer'))
  );
}

/**
 
* Implementation of hook_menu().
*/
function campaign_thermometer_menu() {
  $items = array();

  $items['campaignwidget'] = array(
    'title' => 'Avancement de la campagne',
    'page callback' => 'campaignwidget',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
 
function campaignwidget() {
  $return_page.=monthly_log('2015-12-00');
  return $return_page;
}

function get_donations_amount($date) {
  global $base_url;

  $str_return.=" ".french_month($month)." ".$year." à notre association via notre interface de dons en ligne.</p>
<p><a href=\"$base_url/civicrm/contribute/transact?reset=1&id=2\" title=\"Soutenez-nous\">Vous aussi, effectuez un don à Wikimédia France pour rejoindre cette liste !</a></p>
<p>Les données de cet aperçu sont présentées automatiquement sans garantie d'exactitude et d'exhaustivité.</p>";
	
  $query = db_select('civicrm_contribution', 'c');
 
  $query
    ->addExpression('FLOOR(SUM(total_amount))', 'amount')
    ->condition('financial_type_id', array(1,3), 'IN') /* 1 : Don, 3 : contribution campagne*/
    ->condition('contribution_status_id', '1')
    ->condition('receive_date', $date,'>=');
 
  $result = $query->execute();

  print_r($result);
}
