<?php
/**
* Implementation of hook_permission().
*/
function campaign_thermometer_permission() {
  return array(
    'access campaign_thermometer' => array('title' => t('Campaign Thermometer'))
  );
}

/*
 * Returns custom content to Drupal
 */
function my_page_function(){
    // Call theme() function, so that Drupal includes the custom-page.tpl.php template
    return theme('thermometer-widget');
}

/**
 
* Implementation of hook_menu().
*/
function campaign_thermometer_menu() {
  $items = array();

  $items['campaignwidget'] = array(
    'title' => 'Avancement de la campagne',
    'page callback' => 'campaignwidget',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );

    return $items;
}

/*
 * Implementation of hook_theme().
 */
function campaign_thermometer_theme(){
    return array(
        'campaign_thermometer_template' => array(
            // file name will be custom-page.tpl.php
            'template' => 'thermometer-widget',
        ),
    );
}
 
function campaignwidget() {
  $return_page=get_donations_amount('2015-12-00');
  return $return_page;
}

function get_donations_amount($date) {
  global $base_url;

  $str_return= '';
  	
  $query = db_select('civicrm_contribution', 'c');
 
  $query
    ->condition('financial_type_id', array(1,3), 'IN') /* 1 : Don, 3 : contribution campagne*/
    ->condition('contribution_status_id', '1')
    ->condition('receive_date', $date,'>=');
  $query->addExpression('FLOOR(SUM(total_amount))', 'amount');
 
  $result = $query->execute()->fetchAll();;
  $data = (array)$result[0];
  $amount = $data['amount'];

  $str_return.="<div id=\"donations-thermometer\">
  <h3>On a besoin de vous !</h3>
  <p>$amount / 300 000
  <p>Wikimédia France ne vit que grâce à vous.</p>
<p><a href=\"$base_url/civicrm/contribute/transact?reset=1&id=2\" title=\"Soutenez-nous\">Soutenez-nous !</a></p>
</div>";
  
  print_r($result);
  return $str_return;
}